name: GitlabSync

on:
  push:
  delete:
  fork:

jobs:
  sync:
    uses: rohitthakral/ci-cd/.github/workflows/gitlab-sync.yml@main
    with:
      profile-only: true
      target-url: https://git.ti2.in/odoo-dev-team/absolute_nutrition/absolute-nutrition.git
